inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - _scratchpad.rb

Style/FileName:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/VariableName:
  Enabled: false

Style/FormatString:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - test/validateReadme.rb

Style/MutableConstant:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false
